import { getTimePeriod } from "../../utils/getTimePeriod";
import { Header } from "../../components/common/Header";
import Head from "next/head";
import { Box, Card, Grid, useMediaQuery, useTheme } from "@mui/material";
import { MainChart } from "../../components/dasboard/MainChart";
import { Accounts } from "../../components/dasboard/Accounts";
import { Transactions } from "../../components/dasboard/Transactions";
import { useUserStore } from "@/src/store/userStore";
import { ExpenseChart } from "@/src/components/dasboard/ExpenseChart";
import { useEffect } from "react";
const dashboard = () => {
  const timePeriod = getTimePeriod();
  const theme = useTheme();
  const smScreen = useMediaQuery(theme.breakpoints.down("md"));
  const user = useUserStore((state) => state.user);
  const chartHeight = smScreen ? 280 : 350;

  // useEffect(() => {
  //   console.log(user);
  // }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? (
        <Box m="20px">
          <Box m="10px 0">
            <Header
              title1={`${timePeriod}`}
              title2={`${user?.first_name}`}
              subtitle="Welcome to your dashboard"
            />
          </Box>
          <Grid
            container
            rowSpacing={2}
            columnSpacing={{ xs: 1, sm: 2, md: 3 }}
          >
            <Grid item xs={12} sm={12} md={7}>
              <Grid container rowSpacing={2}>
                <Grid item xs={12}>
                  <ExpenseChart chartHeight={chartHeight} />
                  {/* <MainChart /> */}
                </Grid>
                {smScreen && (
                  <Grid item xs={12}>
                    <Accounts />
                  </Grid>
                )}
                <Grid item xs={12}>
                  <Transactions />
                </Grid>
              </Grid>
            </Grid>
            {!smScreen && (
              <Grid item xs={12} sm={12} md={5}>
                <Accounts />
              </Grid>
            )}
          </Grid>
        </Box>
      ) : null}
    </>
  );
};

export default dashboard;
