import { getTimePeriod } from "../../utils/getTimePeriod";
import { Header } from "../../components/common/Header";
import Head from "next/head";
import { Box } from "@mui/material";
const dashboard = () => {
  const timePeriod = getTimePeriod();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box m="20px">
        <Box m="10px 0">
          <Header
            title1={`${timePeriod}`}
            title2="Shubham"
            subtitle="Welcome to your dashboard"
          />
        </Box>
      </Box>
    </>
  );
};

export default dashboard;
